# This file is for Jekyll-specific production configuration.
# For Open SDG production config, see: _data/site_config_prod.yml

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
environment: production
