# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Open SDG version
remote_theme: brockfanning/open-sdg@footer-field-display-fix

# Site settings
title: U.K. Indicators For The Sustainable Development Goals
description: Data Platform Prototype
baseurl: "/sdg-indicators" # the subpath of your site, e.g. /blog
url: ""
data_dir: data
environment: staging

remote_data_prefix: "https://ONSdigital.github.io/sdg-data"



ignored_disaggregations:
  - Age (default)
  - Activity (default)
  - Urbanisation (default)

graph_title_from_series: true

create_goals:
  layout: goal
create_indicators:
  layout: indicator
create_pages:
  - folder: /
    layout: frontpage
    title: 17 goals to transform our world
  - folder: /goals
    layout: goals
    title: UK data for the Sustainable Development Goals
  - folder: /reporting-status
    layout: reportingstatus
    title: Reporting Status
  - filename: indicators.json
    folder: /
    layout: indicator-json
  - folder: /search
    layout: search
    title: Search results

# Social media accounts.
twitter: 'ONS'

disclaimer:
  phase: BETA
  message: This website is in development – your <a href="https://www.surveymonkey.co.uk/r/SDGfeedback">feedback</a> will help us to improve it

# Email accounts
email_contacts:
  questions: sustainabledevelopment@ons.gov.uk
  suggestions: sustainabledevelopment@ons.gov.uk
  functional: sustainabledevelopment@ons.gov.uk

# Github Repo for Data
repo_name: sdg-data
branch: develop
org_name: ONSdigital

# Build settings
markdown: kramdown

# Date format
date_formats:
  - type: standard
    language: en
    format: "%d %B %Y"

# Travis Support
exclude: [vendor, scripts, remotedata, .sass-cache, Makefile, node_modules]

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: UK
  adjective: UK

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /updates/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Hide categories section of news page
news:
  category_links: false

# The list of languages that are translated. The first one is the default.
languages:
  - en

# Goal image options
goal_image_base: https://open-sdg.github.io/sdg-translations/assets/img/goals
goal_image_extension: svg

# Accessibility options
accessible_tabs: true
accessible_charts: true

# Use single toggle button for controlling high contrast
contrast_type: single

# Use radio buttons for Series instead of dropdown
series_toggle: true

#Header
header:
    include: header-menu-left-aligned.html

# Header Menu
menu:
  # Use these to customise the main navigation.
  - path: /goals
    translation_key: general.goals
  - path: /reporting-status/
    translation_key: menu.reporting_status
  - path: /about/
    translation_key: menu.about
  - path: /publications/
    translation_key: menu.publications
  - path: /faq/
    translation_key: menu.faq
  - path: /updates/
    translation_key: menu.updates

# Footer Menu
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: https://twitter.com/ONS
    translation_key: general.twitter
  - path: /cookies-no-javascript/
    translation_key: menu.cookies
  - path: /privacy-notice/
    translation_key: Privacy
  - path: /accessibility-statement/
    translation_key: Accessibility statement

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

# Apply any custom Javascript.
custom_js:
  - /assets/js/custom.js

search_index_extra_fields:
  - indicator_available
  - graph_title
  - data_keywords

# Graphs
graph_color_set: accessible

hide_single_series: true
hide_single_unit: true

favicons: favicon.io

# Mapping
map_options:
  tileURL: https://{s}.tile.jawg.io/{id}/{z}/{x}/{y}{r}.png?access-token={accessToken}
  tileOptions:
    id: jawg-light
    accessToken: lCtbMZiG4tbVWl7uq9EEch1yphnuLx9JyZL2qZwoQJ26wAu73oK1NkU4K50AALkp
    attribution:  <a href="http://jawg.io" title="Tiles Courtesy of Jawg Maps" target="_blank">&copy; <b>Jawg</b>Maps</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors | <a href="http://geoportal.statistics.gov.uk/">ONS</a>
  minZoom: 4

map_layers:
  - min_zoom: 4
    max_zoom: 6
    staticBorders: true
    subfolder: country
    label: Country
  - min_zoom: 6
    max_zoom: 8
    staticBorders: true
    subfolder: regions
    label: Regions
  - min_zoom: 9
    max_zoom: 12
    staticBorders: true
    subfolder: local_authorities
    label: Local Authorities

survey_url: https://www.surveymonkey.co.uk/r/XFJZGVL

goals_page:
    title: UK data for the Sustainable Development Goals
    description: Click on each goal for UK Sustainable Development Goal global indicator data.

reporting_status:
    disaggregation_tabs: true
    description: |

      Reporting status provides an overview of how much Sustainable Development Goal (SDG) data the UK reports. For more information, see [What does the reporting status mean?](https://onsdigital.github.io/sdg-indicators/faq/#what-does-the-reporting-status-mean)

      Disaggregation status provides an overview of how many of the SDG indicators are disaggregated. For more information, see [What does the disaggregation status mean?](https://onsdigital.github.io/sdg-indicators/faq/#what-does-the-disaggregation-status-mean)

      For details about all available disaggregations and how each indicator is disaggregated, see the [UK disaggregation report](https://onsdigital.github.io/sdg-data/disaggregations.html).

      Note: These percentages have been rounded. As a result, adding them together may not equal exactly 100%.


frontpage_introduction_banner:
  title: 17 goals to transform our world
  description: <a href="https://sdgs.un.org/goals">The Sustainable Development Goals (SDGs)</a> are a universal call to action to end poverty, protect the planet and improve the lives and prospects of everyone, everywhere. The 17 Goals were adopted by all UN Member States in 2015, as part of the <a href="https://sdgs.un.org/2030agenda">2030 Agenda for Sustainable Development</a>.


# This controls the text that appears above the goals grid.
frontpage_goals_grid:
  title: UK data for the Sustainable Development Goals
  description: Click on each goal for UK Sustainable Development Goal global indicator data.


# This controls the three-column "cards" that appear below the goals grid.
frontpage_cards:
  - title: Download all data
    # This "feature" is used for baked-in stuff like "bulk_download".
    include: components/download-all-data.html
    # Optionally control the color of the line above the card title.
  - title: Publications
    content: |

      [SDGs in the UK: Progress on monitoring and reporting data](https://www.ons.gov.uk/economy/environmentalaccounts/articles/sustainabledevelopmentgoalstakingstockprogressandpossibilities/december2020)

      [UK SDG Voluntary National Review](https://www.gov.uk/government/publications/uks-voluntary-national-review-of-the-sustainable-development-goals)
      <br/><br/>
      <a href="./publications" aria-label="More publications">More publications...</a>
  - title: Useful resources
    # Control the content of the card - can use Markdown.
    content: |

      [The Global Goals](https://www.globalgoals.org/)

      [Implementing the Sustainable Development Goals](https://www.gov.uk/government/publications/implementing-the-sustainable-development-goals/implementing-the-sustainable-development-goals--2)

      [UN Department of Economic and Social Affairs](https://sdgs.un.org/)

cookie_consent_form:
  enabled: true

hotjar: false

progress_status:
  status_heading: 'Progress status for 2021:'
  status_types:
    - value: not_measured
      label: Not measured
    - value: no_target_exists
      label: No target exists
    - value: very_far_from_target
      label: Very far from 2030 target
      image: assets/img/progress/very-far-from-target.png
      alt: Progress bar showing progress status for 2022 at level one out of five - Very far from 2030 target
    - value: far_from_target
      label: Far from 2030 target
      image: assets/img/progress/far-from-target.png
      alt: Progress bar showing progress status for 2022 at level two out of five - Far from 2030 target
    - value: moderate_distance_to_target
      label: Moderate distance to target
      image: assets/img/progress/moderate-distance-to-target.png
      alt: Progress bar showing progress status for 2022 at level three out of five - Moderate distance to 2030 target
    - value: close_to_target
      label: Close to 2030 target
      image: assets/img/progress/close-to-target.png
      alt: Progress bar showing progress status for 2022 at level four out of five - Close to 2030 target
    - value: target_achieved
      label: 2030 target achieved
      image: assets/img/progress/target-achieved.png
      alt: Progress bar showing progress status for 2022 at level five out of five - 2030 target achieved
      
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
  - scope: related_indicators
    title: Related Indicators
    description: ''
  - scope: related_publications
    title: Related Publications
    description: ''
