# Jekyll configuration for Open SDG platform

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
remote_theme: brockfanning/open-sdg@indicator-id-in-data-rounding

#UK-specific config settings
survey_url: https://www.surveymonkey.co.uk/r/XFJZGVL
hotjar: false

# Site settings
title: U.K. Indicators For The Sustainable Development Goals
url: ""
environment: staging

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /updates/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
  - jekyll-toc

# Exclude some files/folders.
exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE

country:
  name: UK
  adjective: UK

baseurl: "/sdg-indicators"

opensdg.dataRounding = function(value, context) {
    // Round to 3 decimal places in indicator 3.1.1.
    if (context.indicatorId === 'indicator_3-1-1') {
        return Math.round(value * 1000) / 1000;
    }
    // Otherwise round to 2 decimal places.
    else {
        return Math.round(value * 100) / 100;
    }
}
